// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // The Prisma CLI (migrate/studio) uses a direct/session connection.
    // The app runtime connects via DATABASE_URL (transaction pooler) in
    // src/lib/prisma.ts. Fall back to DATABASE_URL if DIRECT_URL is unset.
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
